arch: dinov3
mode: zeroshot
fullsup: False
lambda_pc: 0.01    # 0 0.01
lambda_dpt: 0.001   # 0 0.001
train_pct: 0.2   # 0.2, 0.4, 0.6, 0.8
save_dir: ./outputs/ssdc-ratio/kahramanrarus/pcdpt   # raw pc dpt pcdpt

# Specific Source Domain Combination (SSDC) setting
# "gaziantep","hatay","kahramanrarus","kirikhan","nurdagi","sackcagozu","satirhuyuk","sekeroba","turkoglu"
source_regions: ["kahramanrarus"]
target_regions: ["gaziantep","hatay","kirikhan","nurdagi","sackcagozu","satirhuyuk","sekeroba","turkoglu"]
